[package]
name = "_skin_engine_rs"
version.workspace = true
edition.workspace = true

[lib]
name = "_skin_engine_rs"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "skin_engine_rs"

[dependencies]
pyo3 = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json.workspace = true
lazy_static.workspace = true
once_cell.workspace = true
regex.workspace = true
serde_yaml = "0.9"
dirs = "5"
