[package]
name = "file_ops_rs"
version.workspace = true
edition = "2021"

[package.metadata.maturin]
name = "file_ops_rs"

[lib]
name = "_file_ops_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json.workspace = true
serde_yaml = "0.9"
regex = { workspace = true }
dirs = "5"
walkdir = "2"
