[package]
name = "rust_redact"
version.workspace = true
edition.workspace = true

[lib]
name = "rust_redact"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3.workspace = true
regex.workspace = true
once_cell.workspace = true

[package.metadata.maturin]
name = "rust_redact"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
