[package]
name = "_honcho_http_rs"
version.workspace = true
edition.workspace = true

[package.metadata.maturin]
name = "_honcho_http_rs"

[lib]
name = "_honcho_http_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest = { workspace = true }
tokio.workspace = true
once_cell.workspace = true
